{% set name = "eslint-plugin-prettier" %}
{% set version = "4.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/prettier/eslint-plugin-prettier/archive/refs/tags/v{{ version }}.tar.gz
  sha256: a55abf22ebda6bfe8ceca5f49807ad5549e80b0e23c22997bfd658e57a9f627c

build:
  skip: true  # [win]
  number: 0

requirements:
  build:
    - nodejs
  host:
    - nodejs
    - yarn
  run:
    - nodejs

test:
  commands:
    - test -d $PREFIX/lib/node_modules/eslint-plugin-prettier  # [unix]
    - if not exist %LIBRARY_INC%\lib\node_modules\eslint-plugin-prettier exit 1  # [win]

about:
  home: https://github.com/prettier/eslint-plugin-prettier
  license: MIT
  license_file:
    - LICENSE.md
    - ThirdPartyLicenses.txt
  summary: Find and fix problems in your JavaScript code.

extra:
  recipe-maintainers:
    - xhochy
    - jens-ox
